// src\app\admin\layout.tsx
import { withAdminPrefix } from "@utils/resourceWithPrefix"; // path ini sesuaikan dengan tempat kamu simpan file-nya
import { useNotificationProvider } from "@refinedev/antd";
import { Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";
import {
  DollarOutlined,
  InfoCircleOutlined,
  CalendarOutlined,
  BookOutlined,
  UserOutlined,
  EnvironmentOutlined,
  HomeOutlined, } from "@ant-design/icons";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ColorModeContextProvider } from "@contexts/color-mode";
import { authProviderClient } from "@providers/auth-provider/auth-provider.client";
import { dataProvider } from "@providers/data-provider";
import "@refinedev/antd/dist/reset.css";
import { FullScreenLoader } from "@/components/FullScreenLoader";

export const metadata: Metadata = {
  title: "Si Masjid",
  description: "Generated by create refine app",
  icons: {
    icon: "/well.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      <body>
        <Suspense>
          <Suspense fallback={<FullScreenLoader />}></Suspense>
          <RefineKbarProvider>
            <AntdRegistry>
              <ColorModeContextProvider defaultMode={defaultMode}>
                
                  <Refine
                    routerProvider={routerProvider}
                    dataProvider={dataProvider}
                    notificationProvider={useNotificationProvider}
                    authProvider={authProviderClient}
                    resources={withAdminPrefix([
                      {
                        name: "home",
                        list: "/home",
                        icon: <HomeOutlined />,
                        options: {
                          label: "Home",
                        },
                      },
                      {
                        name: "transaksi",
                        list: "/transaksi",
                        create: "/transaksi/create",
                        edit: "/transaksi/edit/:id",
                        show: "/transaksi/show/:id",
                        icon: <DollarOutlined />,
                        options: {
                          label: "Keuangan",
                        },
                      },
                      {
                        name: "informasi",
                        list: "/informasi",
                        create: "/informasi/create",
                        edit: "/informasi/edit/:id",
                        show: "/informasi/show/:id",
                        icon: <InfoCircleOutlined />,
                        options: {
                          label: "Informasi",
                        },
                      },
                      {
                        name: "kegiatan",
                        list: "/kegiatan",
                        create: "/kegiatan/create",
                        edit: "/kegiatan/edit/:id",
                        show: "/kegiatan/show/:id",
                        icon: <CalendarOutlined />,
                        options: {
                          label: "Kegiatan",
                        },
                      },
                      {
                        name: "reservasi",
                        list: "/reservasi",
                        create: "/reservasi/create",
                        edit: "/reservasi/edit/:id",
                        show: "/reservasi/show/:id",
                        icon: <BookOutlined />,
                        options: {
                          label: "Reservasi",
                        },
                      },
                      {
                        name: "tempat_reservasi",
                        list: "/tempat_reservasi",
                        create: "/tempat_reservasi/create",
                        edit: "/tempat_reservasi/edit/:id",
                        show: "/tempat_reservasi/show/:id",
                        icon: <EnvironmentOutlined />,
                        options: {
                          label: "Tempat Reservasi",
                        },
                      },
                      // {
                      //   name: "donasi",
                      //   list: "/donasi",
                      //   create: "/donasi/create",
                      //   edit: "/donasi/edit/:id",
                      //   show: "/donasi/show/:id",
                      //   icon: <HeartOutlined />,
                      //   options: {
                      //     label: "Donasi",
                      //   },
                      // },
                      {
                        name: "user",
                        list: "/user",
                        create: "/user/create",
                        edit: "/user/edit/:id",
                        show: "/user/show/:id",
                        icon: <UserOutlined />,
                        options: {
                          label: "Admin",
                        },
                      },
                      // {
                      //   name: "blog_posts",
                      //   list: "/blog-posts",
                      //   create: "/blog-posts/create",
                      //   edit: "/blog-posts/edit/:id",
                      //   show: "/blog-posts/show/:id",
                      //   meta: {
                      //     canDelete: true,
                      //   },
                      // },
                      // {
                      //   name: "categories",
                      //   list: "/categories",
                      //   create: "/categories/create",
                      //   edit: "/categories/edit/:id",
                      //   show: "/categories/show/:id",
                      //   meta: {
                      //     canDelete: true,
                      //   },
                      // },
                      // {
                      //   name: "role",
                      //   list: "/role",
                      //   create: "/role/create",
                      //   edit: "/role/edit/:id",
                      //   show: "/role/show/:id",
                      //   icon: <LockOutlined />,
                      //   options: {
                      //     label: "Role",
                      //   },
                      // },
                    ])}
                    options={{
                      syncWithLocation: true,
                      warnWhenUnsavedChanges: true,
                      useNewQueryKeys: true,
                      projectId: "0Kl6wx-MU7Nf9-WG7uov",
                      // redirect: { default: "/home"},
                    }}
                  >
                    {children}
                    <RefineKbar />
                  </Refine>
                
              </ColorModeContextProvider>
            </AntdRegistry>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}

